# Generated by Django 4.2.6 on 2024-01-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(choices=[('Дохід', 'Дохід'), ('Витрата', 'Витрата')], max_length=10),
        ),
    ]
